version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rhogoron
      MONGO_INITDB_ROOT_PASSWORD: rhogoron
      MONGO_INITDB_DATABASE: myDatabase
    ports:
      - "27017:27017"
    command: ["--auth"]
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rhogoron
      ME_CONFIG_MONGODB_ADMINPASSWORD: rhogoron
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: "1"
      ME_CONFIG_BASICAUTH_PASSWORD: "1"
