server:
  port: 8089

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service-route-post-register-phone
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/register/phone
            - Method=POST

        - id: auth-service-route-post-login
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/login
            - Method=POST

        - id: auth-service-route-put-refresh-token
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/refresh-token
            - Method=PUT
          filters:
            - name: JwtAuth
              args:
                requiredRole: EMPLOYEE

        - id: auth-service-route-get-user
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/user
            - Method=GET
          filters:
            - name: JwtAuth
              args:
                requiredRole: EMPLOYEE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
